### ISSUE TITLE
Integration between Edge monitoring and refactoring/optimization 

### ISSUE THREAD

**Issue by rosogon** [SODALITE-EU/monitoring-system#3]
I open this ticket to start exploring this integration. 

@pmundt  could you provide here what monitoring info could be obtained from the edge?

@IndikaKuma , @kartshy to identify if the metrics are enough or need additional metrics.

**Comment by pmundt** [comment]
In the Edge case we basically have the following different domains to monitor:

- Application-specific metrics collected across the deployed Edge-local microservices
  * Number of requests per service
  * Rate of requests per service
- The Edge Gateway Platform itself
  * CPU temperature
  * Network bandwidth
  * Ambient temperature within the Gateway housing (where supported)
- Heterogeneous Accelerators (GPU, EdgeTPU, etc.) - both integrated, and attached
  * Number of devices
  * Device temperature
  * Utilization rate
- Vehicle ECUs (e.g. via OBD-II) - this is more for the benefit of the driver and the fleet manager
  * Engine RPMs/speed/temperature
  * Coolant temperature
  * Fuel levels / consumption rate
  * Vehicle diagnostic (error) codes
- Kubernetes-specific tunables
  * Utilization resource limits (%age of CPU, GPU, etc. that can be utilized)
  * Ingress/egress traffic shaping and limitation
  * Number of active Pods / services

The application-level metrics are handled via Prometheus already, while others (like the ECUs) push into dedicated MQTT topics. For the accelerators, there are already prometheus exporters for most of these, but as far as I know, nothing for MQTT-based monitoring. For the Kubernetes tunables, I have not looked at this yet, but I would assume someone already has - presumably with prometheus as well.

**Comment by rosogon** [comment]
@pmundt , this is great

If some of these are already handled by Prometheus, @MarioMartReq could check if we can plug it to the Prometheus in the cloud testbed. Please, discuss this with Paul.

@IndikaKuma , @kartshy: next step is to identify if the metrics are enough or need additional metrics.  But I feel the application specific metrics fit well for refactoring.

**Comment by pmundt** [comment]
All of the exporters are now being handled through Prometheus, with Alertmanager alerting rules providing the basis for triggering refactoring.
